### ISSUE TITLE
echarts-china-cities-js/ 里的 js 文件执行 decompress 报错

### ISSUE THREAD

**Issue by chenjiandongx** [echarts-maps/echarts-china-misc-js#1]
![image](https://user-images.githubusercontent.com/19553554/37206352-4b258d58-23d3-11e8-8d8e-ff658864f6bf.png)

echarts-china-provinces-js/ 的没问题

**Comment by chfw** [comment]
which file? I think you got a file non-minified javascript file

**Comment by chenjiandongx** [comment]
广东文件夹下的文件

**Comment by chfw** [comment]
src files have not compression and so far, it is not possible to do decompress on them. the reason is: there are many forms of javascript style. no way to dictate one

`decompress` decompresses the files that are compressed by `compress`, vice versa.
