### ISSUE TITLE
一直报错china-regions.js:13 ECharts is not Loaded

### ISSUE THREAD

**Issue by inputherf** [echarts-maps/echarts-china-misc-js#3]
我在vue中使用，
`import echarts from 'echarts'
import '../../utils/china-regions'`
已经这样引入，但是还是报错，在main.js中引入，china-regions.js还是报错这个。使用的echarts的版本是最新的，所以是否跟版本有关系呢？

**Comment by chfw** [comment]
我用的是 require

**Comment by inputherf** [comment]
希望大佬出一个vue版本！跪求！我一直无法解决这个报错，用require还是报错这样。不知道怎么办

**Comment by inputherf** [comment]
已经用更加粗暴的办法解决，谢谢大佬！

**Comment by chfw** [comment]
我会出 geojson 的版本，应该就可以了。
